/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as DistributeRouteImport } from './routes/distribute'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrepareIdRouteImport } from './routes/prepare.$id'
import { Route as DistributeIdRouteImport } from './routes/distribute.$id'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiPublicPollFirefliesRouteImport } from './routes/api/public/poll-fireflies'
import { Route as ApiPublicFirefliesWebhookRouteImport } from './routes/api/public/fireflies-webhook'
import { Route as AuthenticatedAppMatrixRouteImport } from './routes/_authenticated/app/matrix'
import { Route as AuthenticatedAppChecklistRouteImport } from './routes/_authenticated/app/checklist'
import { Route as AuthenticatedAppMatrixIdRouteImport } from './routes/_authenticated/app/matrix.$id'
import { Route as AuthenticatedAppChecklistIdRouteImport } from './routes/_authenticated/app/checklist.$id'

const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributeRoute = DistributeRouteImport.update({
  id: '/distribute',
  path: '/distribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareIdRoute = PrepareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrepareRoute,
} as any)
const DistributeIdRoute = DistributeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistributeRoute,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const ApiPublicPollFirefliesRoute = ApiPublicPollFirefliesRouteImport.update({
  id: '/api/public/poll-fireflies',
  path: '/api/public/poll-fireflies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirefliesWebhookRoute =
  ApiPublicFirefliesWebhookRouteImport.update({
    id: '/api/public/fireflies-webhook',
    path: '/api/public/fireflies-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppMatrixRoute = AuthenticatedAppMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppChecklistRoute =
  AuthenticatedAppChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMatrixIdRoute =
  AuthenticatedAppMatrixIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMatrixRoute,
  } as any)
const AuthenticatedAppChecklistIdRoute =
  AuthenticatedAppChecklistIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppChecklistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRouteWithChildren
  '/app/matrix': typeof AuthenticatedAppMatrixRouteWithChildren
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/checklist/$id': typeof AuthenticatedAppChecklistIdRoute
  '/app/matrix/$id': typeof AuthenticatedAppMatrixIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRouteWithChildren
  '/app/matrix': typeof AuthenticatedAppMatrixRouteWithChildren
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/checklist/$id': typeof AuthenticatedAppChecklistIdRoute
  '/app/matrix/$id': typeof AuthenticatedAppMatrixIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/_authenticated/app/checklist': typeof AuthenticatedAppChecklistRouteWithChildren
  '/_authenticated/app/matrix': typeof AuthenticatedAppMatrixRouteWithChildren
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/checklist/$id': typeof AuthenticatedAppChecklistIdRoute
  '/_authenticated/app/matrix/$id': typeof AuthenticatedAppMatrixIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/app'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/app/checklist'
    | '/app/matrix'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
    | '/app/'
    | '/app/checklist/$id'
    | '/app/matrix/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/app/checklist'
    | '/app/matrix'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
    | '/app'
    | '/app/checklist/$id'
    | '/app/matrix/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/_authenticated/app'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/_authenticated/app/checklist'
    | '/_authenticated/app/matrix'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
    | '/_authenticated/app/'
    | '/_authenticated/app/checklist/$id'
    | '/_authenticated/app/matrix/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DistributeRoute: typeof DistributeRouteWithChildren
  MeetingRoute: typeof MeetingRoute
  PrepareRoute: typeof PrepareRouteWithChildren
  AnalysisIdRoute: typeof AnalysisIdRoute
  ApiPublicFirefliesWebhookRoute: typeof ApiPublicFirefliesWebhookRoute
  ApiPublicPollFirefliesRoute: typeof ApiPublicPollFirefliesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribute': {
      id: '/distribute'
      path: '/distribute'
      fullPath: '/distribute'
      preLoaderRoute: typeof DistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare/$id': {
      id: '/prepare/$id'
      path: '/$id'
      fullPath: '/prepare/$id'
      preLoaderRoute: typeof PrepareIdRouteImport
      parentRoute: typeof PrepareRoute
    }
    '/distribute/$id': {
      id: '/distribute/$id'
      path: '/$id'
      fullPath: '/distribute/$id'
      preLoaderRoute: typeof DistributeIdRouteImport
      parentRoute: typeof DistributeRoute
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/public/poll-fireflies': {
      id: '/api/public/poll-fireflies'
      path: '/api/public/poll-fireflies'
      fullPath: '/api/public/poll-fireflies'
      preLoaderRoute: typeof ApiPublicPollFirefliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fireflies-webhook': {
      id: '/api/public/fireflies-webhook'
      path: '/api/public/fireflies-webhook'
      fullPath: '/api/public/fireflies-webhook'
      preLoaderRoute: typeof ApiPublicFirefliesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/matrix': {
      id: '/_authenticated/app/matrix'
      path: '/matrix'
      fullPath: '/app/matrix'
      preLoaderRoute: typeof AuthenticatedAppMatrixRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/checklist': {
      id: '/_authenticated/app/checklist'
      path: '/checklist'
      fullPath: '/app/checklist'
      preLoaderRoute: typeof AuthenticatedAppChecklistRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/matrix/$id': {
      id: '/_authenticated/app/matrix/$id'
      path: '/$id'
      fullPath: '/app/matrix/$id'
      preLoaderRoute: typeof AuthenticatedAppMatrixIdRouteImport
      parentRoute: typeof AuthenticatedAppMatrixRoute
    }
    '/_authenticated/app/checklist/$id': {
      id: '/_authenticated/app/checklist/$id'
      path: '/$id'
      fullPath: '/app/checklist/$id'
      preLoaderRoute: typeof AuthenticatedAppChecklistIdRouteImport
      parentRoute: typeof AuthenticatedAppChecklistRoute
    }
  }
}

interface AuthenticatedAppChecklistRouteChildren {
  AuthenticatedAppChecklistIdRoute: typeof AuthenticatedAppChecklistIdRoute
}

const AuthenticatedAppChecklistRouteChildren: AuthenticatedAppChecklistRouteChildren =
  {
    AuthenticatedAppChecklistIdRoute: AuthenticatedAppChecklistIdRoute,
  }

const AuthenticatedAppChecklistRouteWithChildren =
  AuthenticatedAppChecklistRoute._addFileChildren(
    AuthenticatedAppChecklistRouteChildren,
  )

interface AuthenticatedAppMatrixRouteChildren {
  AuthenticatedAppMatrixIdRoute: typeof AuthenticatedAppMatrixIdRoute
}

const AuthenticatedAppMatrixRouteChildren: AuthenticatedAppMatrixRouteChildren =
  {
    AuthenticatedAppMatrixIdRoute: AuthenticatedAppMatrixIdRoute,
  }

const AuthenticatedAppMatrixRouteWithChildren =
  AuthenticatedAppMatrixRoute._addFileChildren(
    AuthenticatedAppMatrixRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppChecklistRoute: typeof AuthenticatedAppChecklistRouteWithChildren
  AuthenticatedAppMatrixRoute: typeof AuthenticatedAppMatrixRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppChecklistRoute: AuthenticatedAppChecklistRouteWithChildren,
  AuthenticatedAppMatrixRoute: AuthenticatedAppMatrixRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DistributeRouteChildren {
  DistributeIdRoute: typeof DistributeIdRoute
}

const DistributeRouteChildren: DistributeRouteChildren = {
  DistributeIdRoute: DistributeIdRoute,
}

const DistributeRouteWithChildren = DistributeRoute._addFileChildren(
  DistributeRouteChildren,
)

interface PrepareRouteChildren {
  PrepareIdRoute: typeof PrepareIdRoute
}

const PrepareRouteChildren: PrepareRouteChildren = {
  PrepareIdRoute: PrepareIdRoute,
}

const PrepareRouteWithChildren =
  PrepareRoute._addFileChildren(PrepareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DistributeRoute: DistributeRouteWithChildren,
  MeetingRoute: MeetingRoute,
  PrepareRoute: PrepareRouteWithChildren,
  AnalysisIdRoute: AnalysisIdRoute,
  ApiPublicFirefliesWebhookRoute: ApiPublicFirefliesWebhookRoute,
  ApiPublicPollFirefliesRoute: ApiPublicPollFirefliesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
