/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as ApiPublicPollFirefliesRouteImport } from './routes/api/public/poll-fireflies'
import { Route as ApiPublicFirefliesWebhookRouteImport } from './routes/api/public/fireflies-webhook'

const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPollFirefliesRoute = ApiPublicPollFirefliesRouteImport.update({
  id: '/api/public/poll-fireflies',
  path: '/api/public/poll-fireflies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirefliesWebhookRoute =
  ApiPublicFirefliesWebhookRouteImport.update({
    id: '/api/public/fireflies-webhook',
    path: '/api/public/fireflies-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meeting'
    | '/analysis/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meeting'
    | '/analysis/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  id:
    | '__root__'
    | '/'
    | '/meeting'
    | '/analysis/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingRoute: typeof MeetingRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  ApiPublicFirefliesWebhookRoute: typeof ApiPublicFirefliesWebhookRoute
  ApiPublicPollFirefliesRoute: typeof ApiPublicPollFirefliesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-fireflies': {
      id: '/api/public/poll-fireflies'
      path: '/api/public/poll-fireflies'
      fullPath: '/api/public/poll-fireflies'
      preLoaderRoute: typeof ApiPublicPollFirefliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fireflies-webhook': {
      id: '/api/public/fireflies-webhook'
      path: '/api/public/fireflies-webhook'
      fullPath: '/api/public/fireflies-webhook'
      preLoaderRoute: typeof ApiPublicFirefliesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingRoute: MeetingRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  ApiPublicFirefliesWebhookRoute: ApiPublicFirefliesWebhookRoute,
  ApiPublicPollFirefliesRoute: ApiPublicPollFirefliesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
