/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as DistributeRouteImport } from './routes/distribute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrepareIdRouteImport } from './routes/prepare.$id'
import { Route as DistributeIdRouteImport } from './routes/distribute.$id'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as ApiPublicPollFirefliesRouteImport } from './routes/api/public/poll-fireflies'
import { Route as ApiPublicFirefliesWebhookRouteImport } from './routes/api/public/fireflies-webhook'

const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributeRoute = DistributeRouteImport.update({
  id: '/distribute',
  path: '/distribute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareIdRoute = PrepareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrepareRoute,
} as any)
const DistributeIdRoute = DistributeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistributeRoute,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPollFirefliesRoute = ApiPublicPollFirefliesRouteImport.update({
  id: '/api/public/poll-fireflies',
  path: '/api/public/poll-fireflies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirefliesWebhookRoute =
  ApiPublicFirefliesWebhookRouteImport.update({
    id: '/api/public/fireflies-webhook',
    path: '/api/public/fireflies-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distribute': typeof DistributeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/prepare': typeof PrepareRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/distribute/$id': typeof DistributeIdRoute
  '/prepare/$id': typeof PrepareIdRoute
  '/api/public/fireflies-webhook': typeof ApiPublicFirefliesWebhookRoute
  '/api/public/poll-fireflies': typeof ApiPublicPollFirefliesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  id:
    | '__root__'
    | '/'
    | '/distribute'
    | '/meeting'
    | '/prepare'
    | '/analysis/$id'
    | '/distribute/$id'
    | '/prepare/$id'
    | '/api/public/fireflies-webhook'
    | '/api/public/poll-fireflies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributeRoute: typeof DistributeRouteWithChildren
  MeetingRoute: typeof MeetingRoute
  PrepareRoute: typeof PrepareRouteWithChildren
  AnalysisIdRoute: typeof AnalysisIdRoute
  ApiPublicFirefliesWebhookRoute: typeof ApiPublicFirefliesWebhookRoute
  ApiPublicPollFirefliesRoute: typeof ApiPublicPollFirefliesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribute': {
      id: '/distribute'
      path: '/distribute'
      fullPath: '/distribute'
      preLoaderRoute: typeof DistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare/$id': {
      id: '/prepare/$id'
      path: '/$id'
      fullPath: '/prepare/$id'
      preLoaderRoute: typeof PrepareIdRouteImport
      parentRoute: typeof PrepareRoute
    }
    '/distribute/$id': {
      id: '/distribute/$id'
      path: '/$id'
      fullPath: '/distribute/$id'
      preLoaderRoute: typeof DistributeIdRouteImport
      parentRoute: typeof DistributeRoute
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-fireflies': {
      id: '/api/public/poll-fireflies'
      path: '/api/public/poll-fireflies'
      fullPath: '/api/public/poll-fireflies'
      preLoaderRoute: typeof ApiPublicPollFirefliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fireflies-webhook': {
      id: '/api/public/fireflies-webhook'
      path: '/api/public/fireflies-webhook'
      fullPath: '/api/public/fireflies-webhook'
      preLoaderRoute: typeof ApiPublicFirefliesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DistributeRouteChildren {
  DistributeIdRoute: typeof DistributeIdRoute
}

const DistributeRouteChildren: DistributeRouteChildren = {
  DistributeIdRoute: DistributeIdRoute,
}

const DistributeRouteWithChildren = DistributeRoute._addFileChildren(
  DistributeRouteChildren,
)

interface PrepareRouteChildren {
  PrepareIdRoute: typeof PrepareIdRoute
}

const PrepareRouteChildren: PrepareRouteChildren = {
  PrepareIdRoute: PrepareIdRoute,
}

const PrepareRouteWithChildren =
  PrepareRoute._addFileChildren(PrepareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributeRoute: DistributeRouteWithChildren,
  MeetingRoute: MeetingRoute,
  PrepareRoute: PrepareRouteWithChildren,
  AnalysisIdRoute: AnalysisIdRoute,
  ApiPublicFirefliesWebhookRoute: ApiPublicFirefliesWebhookRoute,
  ApiPublicPollFirefliesRoute: ApiPublicPollFirefliesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
